### ISSUE TITLE
When authenticating via HTTP redirect (Get) the signature is never validated.

### ISSUE THREAD

**Issue by Yanchek99** [saml-idp/saml_idp#42] opened 2016-05-31 18:50 UTC
In SAML when authenticating via the HTTP Redirect (get) path, the signature is a query parameter rather then part of the request body.  Currently there is no handling for this in the gem, so requests are never validated for a signature if using this path.

**Comment by jphenow** [comment] 2020-01-21 23:39
Closing this one since it's a duplicate of #36. Hopefully can get #111 merged soon and resolve these.

**Closed by jphenow** 2020-01-21 23:39 UTC
Labels: duplicate, enhancement
